StudentStats/urls.py
from django.contrib import admin
from django.urls import path, include
from avance_academico import views
from avance_academico.views import get_materias

urlpatterns = [
    path("avance_academico/", include("avance_academico.urls")),
    path("admin/", admin.site.urls),
    path("login/",views.MyLoginView.as_view(),name="login"),
    path('api/materias/', get_materias, name='api_materias'),
]

avance_academico/urls.py
from django.urls import path

from . import views

app_name = "avance_academico"
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("lista_materias/", views.ListaMaterias.as_view(), name="lista-materias"),
    path("lista_profesores/",views.ListaProfesores.as_view(),name="lista-profesores"),

    path("agrega_profesor/",views.agrega_profesor,name="agrega-profesor"),
    path("detail/<int:id>/",views.DetalleMateriaView.as_view(),name="detail-materia"),
    path("detail_profesor/<int:id>/",views.detalleprofesor,name="detail-profesor"),
    path("editaprofesor-<int:id>/",views.editarprofesor,name="edita-profesor-form"),
    path("editamateria-<int:id>/",views.editarmateria,name="edita-materia"),
    path("anotamateria",views.AnotaMaterias.as_view(),name="anota-materias"),
    path("comprobacion<int:id>/",views.VerificaIncripcion,name="verifica-inscripcion"),
    path("estado_carrera/",views.Estadocarrera,name="estado-carrera"),
    path("validadatos/",views.ValidaDatos,name="ingresa-datos"),
    path('buscar_materia', views.buscar_materia, name='buscar_materia'),
    path("materias_carrera",views.MuestraMaterias.as_view(),name="muestra_materias"),
    path("error/",views.errorAnotacion,name="error_anotacion"),
    path("cronograma/",views.cronogramaMaterias,name="cronograma-materias"),
    path('logout/', views.CustomLogoutView.as_view(), name='logout'),
    path('login/',views.MyLoginView.as_view(),name="login")

]

materias/urls.py
from os import path

from materias import views

app_name="materias"
urlpatterns=[
    path("lista_materias/", views.ListaMaterias.as_view(), name="lista-materias"),
    path("detail/<int:id>/",views.detallemateria,name="detail-materia"),
    path("editamateria-<int:id>/",views.editarmateria,name="edita-materia")
]

avance_academico/models.py
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from django.forms import DateField


class Materia(models.Model):
    Tipo_cursada = (
        ('ANUAL', 'ANUAL'),
        ('PRIMER CUATRIMESTRE', 'PRIMER CUATRIMESTRE'),
        ('SEGUNDO CUATRIMESTRE', 'SEGUNDO CUATRIMESTRE')
    )

    Dias_cursada = (
        ("LUNES", "LUNES"), ("MARTES", "MARTES"), ("MIERCOLES", "MIERCOLES"), ("JUEVES", "JUEVES"),
        ("VIERNES", "VIERNES"),
        ("SABADO", "SABADO"))



    # Campos básicos
    codigo = models.CharField(max_length=20)
    nombre = models.CharField(max_length=100)
    anio = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(5)])
    duracion = models.CharField(max_length=50, choices=Tipo_cursada, null=True, blank=True)
    # Relaciones
    correlativas = models.ManyToManyField('self', symmetrical=False, blank=True)
    carrera_materia = models.ManyToManyField('Carrera', symmetrical=False, blank=True, default="carrera")

    dia = models.CharField(max_length=50, choices=Dias_cursada, null=True, blank=True)
    inicio_horario = models.TimeField(blank=True, null=True)
    fin_horario = models.TimeField(blank=True, null=True)


    # Relaciones

    def __str__(self):
        return f"{self.codigo} - {self.nombre}"


class Carrera(models.Model):
    nombre = models.CharField(max_length=200, default="nombre")
    materias=models.IntegerField(default=0)
    titulo_intermedio=models.BooleanField()
    años=models.IntegerField(default=0)
    def __str__(self):
        return f"{self.nombre}"


class Estudiante(models.Model):
    # Campos básicos
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    dni = models.IntegerField(default=0)
    nombre = models.CharField(max_length=200, default="0")
    apellido = models.CharField(max_length=200, default="0")
    alta_admin = models.BooleanField()
    carreras = models.ManyToManyField('Carrera', symmetrical=False, blank=True)

    def __str__(self):
        return f"{self.nombre} {self.apellido} ({self.dni})"


class Profesor(models.Model):
    # campos basicos
    nombre_profesor = models.CharField(max_length=200, default="Nombre")
    apellido_profesor = models.CharField(max_length=200, default="Apellido")
    materias = models.ManyToManyField('Materia', related_name='profesores', symmetrical=False, blank=True)
    def __str__(self):
        return f"{self.nombre_profesor}{self.apellido_profesor}"


class MateriaCursada(models.Model):
    estudiante = models.ForeignKey(Estudiante, on_delete=models.CASCADE)
    materia = models.ForeignKey(Materia, on_delete=models.CASCADE)
    veces_recursada = models.IntegerField(default=0)
    aprobada = models.BooleanField(default=0)
    en_curso = models.BooleanField(default=0)

    def __str__(self):
        return f"{self.estudiante}{self.materia}"


class Calificacion(models.Model):
    materia_cursada = models.ForeignKey(MateriaCursada, on_delete=models.CASCADE)
    Tipo_examen = (
        ('PARCIAL', 'PARCIAL'),
        ('RECUPERATORIO', 'RECUPERATORIO'),
        ('FINAL', 'FINAL')
    )
    tipo = models.CharField(max_length=50, choices=Tipo_examen, null=True, blank=True)
    nota = models.DecimalField(max_digits=3, decimal_places=2)
    fecha = models.DateField()


class ConfiguracionSemestre(models.Model):
    inicio_primer_cuatrimestre = models.DateField()
    fin_primer_cuatrimestre = models.DateField()
    inicio_segundo_cuatrimestre = models.DateField()
    fin_segundo_cuatrimestre = models.DateField()
    @staticmethod
    def obtener_fechas_actuales():
        configuracion = ConfiguracionSemestre.objects.first()
        return {
        "inicio_primer_cuatri": configuracion.inicio_primer_cuatrimestre,
        "fin_primer_cuatri": configuracion.fin_primer_cuatrimestre,
        "inicio_segundo_cuatri": configuracion.inicio_segundo_cuatrimestre,
        "fin_segundo_cuatri": configuracion.fin_segundo_cuatrimestre
        }

avance_academico/forms.py
from django import forms
from django.forms import ModelForm

from .models import Profesor, Materia


class ProfesorForm(forms.Form):
    nombre = forms.CharField(label="Nombre", max_length=100)
    apellido=forms.CharField(label="Apellido",max_length=100)
    dni=forms.CharField(label="Dni",max_length=8)



class ProfesorModel(ModelForm):
    class Meta:
        model = Profesor
        fields = "__all__"

class MateriaModel(ModelForm):
    class Meta:
        model= Materia
        fields="__all__"

avance_academico/views.py
import json
from audioop import reverse
from datetime import datetime, time, timedelta, date
from urllib import request

import networkx as nx
from django import forms
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth import logout
from django.core.serializers import serialize
from django.http import JsonResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views import generic
from django.views.decorators.http import require_GET
from django.views.generic import TemplateView
from pyexpat.errors import messages
from rest_framework.decorators import api_view
from rest_framework.response import Response

from .forms import ProfesorModel, MateriaModel
from .models import Materia, Profesor, Estudiante, MateriaCursada, Calificacion, ConfiguracionSemestre


from rest_framework import serializers
from .models import Materia, Profesor



class ProfesorSerializer(serializers.ModelSerializer):
    class Meta:
        model = Profesor
        fields = ('nombre_profesor', 'apellido_profesor')

class MateriaSerializer(serializers.ModelSerializer):
    profesores = ProfesorSerializer(many=True, read_only=True)
    duracionHoras = serializers.SerializerMethodField()

    class Meta:
        model = Materia
        fields = ('codigo', 'nombre', 'dia', 'inicio_horario', 'fin_horario', 'profesores', 'duracionHoras')

    def get_duracionHoras(self, obj):
        if obj.inicio_horario and obj.fin_horario:
            inicio = datetime.combine(datetime.today(), obj.inicio_horario)
            fin = datetime.combine(datetime.today(), obj.fin_horario)
            duracion = fin - inicio
            return duracion.total_seconds() / 3600
        return 0

@api_view(['GET'])
def get_materias(request):
    estudiante = Estudiante.objects.get(user=request.user)
    materias_encurso = MateriaCursada.objects.filter(estudiante=estudiante, en_curso=1)
    materias_encurso_ids = [materia.materia_id for materia in materias_encurso]
    materias = Materia.objects.filter(id__in=materias_encurso_ids).order_by("inicio_horario").all()
    serializer = MateriaSerializer(materias, many=True)
    return Response(serializer.data)

def cronogramaMaterias(request):
    template_name = "avance_academico/cronograma-materias.html"

    return render(request, template_name)



def ValidaDatos(request):
    return render(request, "avance_academico/valida-datos.html")


def errorAnotacion(materias_faltantes):
    return render(request, template_name="avance_academico/error-anotacion.html",
                  context={"correlativas_no_aprobadas": materias_faltantes})


def Estadocarrera(request):
    estudiante = Estudiante.objects.get(user=request.user)
    cant_materias = len(Materia.objects.all())
    materias_aprobad = MateriaCursada.objects.filter(aprobada=True, estudiante=estudiante).all()
    materias_aprobadas = len(materias_aprobad)
    porcentaje = materias_aprobadas / cant_materias * 100
    aprobadas_finales = Calificacion.objects.filter(tipo="FINAL", nota__gte=4)
    if request.method == "POST":
        form = Cantaños(request.POST)
        cursa_materias = form.data.get("cant_años")
        cant_años_calculados = int((cant_materias - materias_aprobadas) / int(cursa_materias))

        return render(request, "avance_academico/estado-carrera.html",
                      {"estudiante": estudiante, "cant_materias": cant_materias,
                       "materias_aprobadas": materias_aprobad, "cant_aprobadas": materias_aprobadas,
                       "porcentaje": porcentaje, "aprobadas_finales": aprobadas_finales, "form": form,
                       "cant_años_calculados": cant_años_calculados})
    else:
        form = Cantaños()
        return render(request, "avance_academico/estado-carrera.html",
                      {"estudiante": estudiante, "cant_materias": cant_materias,
                       "materias_aprobadas": materias_aprobad, "cant_aprobadas": materias_aprobadas,
                       "porcentaje": porcentaje, "aprobadas_finales": aprobadas_finales, "form": form,
                       })


def VerificaIncripcion(request, id):
    estudiante = Estudiante.objects.get(user=request.user)
    materia = get_object_or_404(Materia, pk=id)
    materias_encurso = MateriaCursada.objects.filter(estudiante=estudiante, en_curso=1)
    materias_encurso_ids = [materia.materia_id for materia in materias_encurso]
    materias = Materia.objects.filter(id__in=materias_encurso_ids).all()
    materias_iguales = materias.filter(dia__contains=materia.dia)
    materias_superpuestas = []
    for materia_tabla in materias_iguales:
        print(materias_iguales)
        if (
                materia.inicio_horario < materia_tabla.fin_horario and materia.inicio_horario >= materia_tabla.inicio_horario) or \
                (
                        materia_tabla.inicio_horario < materia.fin_horario and materia_tabla.inicio_horario >= materia.inicio_horario):
            materias_superpuestas.append(materia_tabla)

    if len(materias_superpuestas) > 0:
        mensaje = f"Error en la inscripción, coincide con la(s) materia(s): {', '.join(str(materia.nombre) for materia in materias_iguales)}"
        return JsonResponse({
            "success": False,
            "message": mensaje,
        })
    else:
        MateriaCursada.objects.create(estudiante=estudiante, materia=materia, en_curso=1)
        return JsonResponse({"success": True})


class AnotaMaterias(LoginRequiredMixin, generic.ListView):
    template_name = "avance_academico/anotarse-materias.html"
    context_object_name = "materias_disponibles"

    def get_queryset(self):
        estudiante = Estudiante.objects.get(user=self.request.user)
        materias_no_disponibles = MateriaCursada.objects.filter(estudiante=estudiante)
        materias_no_disponibles_ids = [materia_cursada.materia_id for materia_cursada in materias_no_disponibles]
        fechas_semestre = ConfiguracionSemestre.obtener_fechas_actuales()
        fecha_actual = datetime.now().date()

        if fecha_actual <= fechas_semestre["fin_primer_cuatri"]:
            materias = Materia.objects.exclude(id__in=materias_no_disponibles_ids).exclude(
                duracion="SEGUNDO CUATRIMESTRE")

        elif fecha_actual < fechas_semestre["inicio_segundo_cuatri"] or fecha_actual > fechas_semestre[
            "fin_segundo_cuatri"]:
            materias = []
        else:
            materias = Materia.objects.exclude(id__in=materias_no_disponibles_ids).filter(
                duracion="SEGUNDO CUATRIMESTRE")
        materias_disponibles = []
        for materia in materias:
            correlativas = materia.correlativas.all()
            correlativas_no_aprobadas = correlativas.exclude(
                id__in=MateriaCursada.objects.filter(estudiante=estudiante, aprobada=True).values_list('materia_id',
                                                                                                       flat=True))
            if not correlativas_no_aprobadas:
                materias_disponibles.append(materia)
        return materias_disponibles


class MyLoginView(LoginView):
    template_name = "avance_academico/login.html"
    redirect_authenticated_user = True

    def get_success_url(self):
        return reverse_lazy('avance_academico:index')


    def form_invalid(self, form):
        messages.error(self.request, 'Invalid username or password')
        return self.render_to_response(self.get_context_data(form=form))

class CustomLogoutView(LogoutView):
    next_page = reverse_lazy('login')
class IndexView(generic.ListView):
    template_name = "avance_academico/index.html"
    context_object_name = ""

    def get_context_data(self, **kwargs):
        usuario = self.request.user  # o de donde sea que obtienes el usuario
        context = super().get_context_data(usuario=usuario, **kwargs)
        # tu lógica adicional aquí
        return context
    def get_queryset(self):
        """Return the last five published questions."""
        return Materia.objects.order_by("-anio")[:50]


@require_GET
def buscar_materia(request):
    query = request.GET.get('q', '')
    if query:
        materias = Materia.objects.filter(nombre__icontains=query)
    else:
        materias = Materia.objects.none()

    resultados = [{'id': materia.id, 'nombre': materia.nombre} for materia in materias]
    return JsonResponse(resultados, safe=False)


class ListaMaterias(LoginRequiredMixin, generic.ListView):
    template_name = "avance_academico/materias_list.html"
    context_object_name = "materia_list"

    def get_queryset(self):
        """Muestra materias"""
        estudiante = Estudiante.objects.get(user=self.request.user)
        materias_aprobadas = MateriaCursada.objects.filter(estudiante_id=estudiante.id, aprobada=1)
        materias_aprobadas_ids = [materia_cursada.materia_id for materia_cursada in materias_aprobadas]
        materias = Materia.objects.filter(id__in=materias_aprobadas_ids)
        return materias


class MuestraMaterias(generic.ListView):
    template_name = "avance_academico/materias_carrera.html"
    context_object_name = "materia_list"

    def get_queryset(self):
        return Materia.objects.order_by("nombre")[:50]


class ListaProfesores(LoginRequiredMixin, generic.ListView):
    template_name = "avance_academico/profesor_list.html"
    context_object_name = "profesor_list"

    def get_queryset(self):
        return Profesor.objects.order_by("nombre_profesor")[:10]


class DetalleMateriaView(TemplateView):
    template_name = "avance_academico/detail_materia.html"

    def get_context_data(self, **kwargs):
        materia = get_object_or_404(Materia, pk=self.kwargs['id'])
        profesores = Profesor.objects.filter(materias=materia.id)
        grafo = construir_grafo(materia.id)
        grafo_json = grafo_to_json(grafo)

avance_academico/templates/avance_academico/anotarse-materias.html
{% extends "avance_academico/base.html" %}
{% block content %}
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Title</title>
    </head>
    <body>
    {% if materias_disponibles %}
    {% for materia in materias_disponibles %}
        <li>
            <a href="{% url 'avance_academico:detail-materia' materia.id %}"> {{ materia.nombre }} </a>
            <button onclick="anotarseEnMateria({{ materia.id }})" class="btn btn-success">Anotarse
            </button>

        </li>
    {% endfor %}
     {% else %}
        <h4>No es posible anotarse en estas fechas</h4>
    {% endif %}
    <div class="modal fade" id="inscripcionModal" tabindex="-1" aria-labelledby="inscripcionModalLabel"
         aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="inscripcionModalLabel"> Anotarse</h5>
                    <button type="button " id="close" class="btn-close" data-bs-dismiss="modal"
                            aria-label="Close"></button>

                </div>
                <div class="modal-body">
                    <form id="inscripcionForm">
                        <!-- Los campos del form los vamos a llenar de forma dinamica con JS -->
                    </form>
                </div>
                <div class="modal-footer">

                    <button type="button" id="cerrar" class="btn btn-secondary" data-bs-dismmis="modal"> Cerrar
                    </button>
                </div>
            </div>
        </div>
    </div>
    </body>
    </html>
    <script>

        function anotarseEnMateria(materia_id) {
            Swal.fire({
                title: "Estas seguro?",
                text: "Puedes volver hacia atras",
                icon: "warning",
                showCancelButton: true,
                confirmButtonColor: "#3085d6",
                cancelButtonColor: "#d33",
                confirmButtonText: "Si, estoy seguro"

            }).then((result) => {
                if (result.isConfirmed) {
                      var url = `{% url 'avance_academico:verifica-inscripcion' 0 %}`.replace('0', materia_id);
            fetch(url)
                .then(response => response.json())
                .then(data => {
                    if (data.success) {
                        Swal.fire({
                        title: "Anotacion exitosa",
                        text: "Te has anotado a una materia",
                        icon: "success"
                    });
                    } else {
                        Swal.fire({
                            icon: 'error',
                            title: 'Error',
                            text: data.message,
                            footer: JSON.stringify(data.details),  // Show details in the footer
                        });
                    }
                })
                .catch(error => console.error('Error:', error));
                }
            });
        }
        setInterval(recargarPagina, 4000);
        function recargarPagina() {
        location.reload();
        }
    </script>
{% endblock %}

avance_academico/templates/avance_academico/error-anotacion.html
{% extends "avance_academico/base.html" %}
{% block content %}
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
                <script type="text/javascript" src="https://unpkg.com/vis-network/standalone/umd/vis-network.min.js"></script>

        <title>Title</title>
    </head>
    <body>

    {% if correlativas_no_aprobadas %}
        <a><h3>ERROR</h3></a>
        <a>Debe las siguientes materias: </a>
        <ul>{% for materia in correlativas_no_aprobadas %}
            <li><a> {{ materia.nombre }}</a></li>
        {% endfor %}</ul>
        <a href="{% url 'avance_academico:anota-materias' %} " class="btn btn-outline-secondary"> Volver a las
            Inscripciones</a></li>
    {% else %}
        <p></p>
    {% endif %}

    </body>
    </html>


{% endblock %}

avance_academico/templates/avance_academico/index.html
{% extends "avance_academico/base.html" %}
{% block content %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Materias</title>
    <!-- Agrega tus enlaces a hojas de estilo (si es necesario) -->
    <style>
        body {
            font-family: "Arial", sans-serif;
            margin: 0;
            padding: 0;
        }

        .container {
            text-align: center;
            margin-top: 20px;
        }

        .btn {
            display: inline-block;
            padding: 12px 20px;
            font-size: 16px;
            text-align: center;
            text-decoration: none;
            background-color: #007bff; /* Azul académico */
            color: white; /* Color de texto blanco */
            border: 1px solid #007bff; /* Borde azul académico */
            border-radius: 5px;
            transition: background-color 0.3s;
            margin: 5px;
        }

        .btn:hover {
            background-color: #0056b3; /* Cambia el color de fondo al pasar el mouse */
        }

        h1 {
            color: #007bff; /* Azul académico */
        }

        p {
            color: #343a40; /* Texto oscuro */
        }

        /* Otros estilos que desees agregar para adaptar la apariencia académica */
    </style>
</head>
<body>
    <div class="header">
        <img src="/static/blito.jpg" alt="Logo de la facultad">
        <h1>Bienvenido a la Universidad Fasta</h1>
    </div>

    {% if request.user.is_authenticated %}
        <div class="container">
            <p>Selecciona una opción:</p>
            <a href="{% url 'avance_academico:muestra_materias' %}" class="btn">Materias Carrera</a>
            <a href="{% url 'avance_academico:lista-profesores' %}" class="btn">Listar profesores</a>
            <a href="{% url 'avance_academico:anota-materias' %}" class="btn">Anotarse a materias</a>
            <a href="{% url 'avance_academico:estado-carrera' %}" class="btn">Estado de la carrera</a>
            <a href="{% url 'avance_academico:ingresa-datos' %}" class="btn">Validar Datos</a>
        </div>
    {% else %}
        {% include "avance_academico/login.html" %}
    {% endif %}
</body>
</html>
{% endblock %}

avance_academico/templates/avance_academico/materias_carrera.html
{% extends "avance_academico/base.html" %}
{% block content %}
    <!doctype html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Title</title>
    </head>
    <body>
    <div id="materia_list" {{ materia_list }}></div>

    {% if materia_list %}

        <input type="text" name="buscador" id="buscador" placeholder="Buscar...">
        <input type="submit" id="submit" value="Enviar">
        <li><a href="{% url 'avance_academico:lista-materias' %}" class="btn btn-outline-secondary"> Tus materias</a>
        <li><a href="{% url 'avance_academico:cronograma-materias' %}" class="btn btn-outline-secondary"> Cronograma</a>
        </li>

    {% else %}
        <p></p>
    {% endif %}
    </body>
    </html>
    <script>
        document.addEventListener('DOMContentLoaded', function () {


            var inputbusqueda = document.getElementById("buscador");
            var url = '{% url 'avance_academico:buscar_materia' %}';

            inputbusqueda.addEventListener("keyup", function () {
                var query = inputbusqueda.value;
                fetch(`${url}?q=${query}`)
                    .then(response => response.json())
                    .then(data => {
                        var lista = materia_list;
                        lista.textContent = ""; //Limpia el contenido de la lista
                        if (lista) {

                            // El elemento existe, ahora puedes usar lista.innerHTML sin preocupaciones
                            console.log(lista);
                        } else {
                            console.error('El elemento con ID "lista-materias" no fue encontrado en el DOM');
                        }
                        var encuentra=false;

                        if (data.length > 0) {
                            data.forEach(materia => {
                                encuentra=true;
                                var li = document.createElement('li');
                                li.classList.add('materia-item');
                                var detalle_url = `{% url 'avance_academico:detail-materia' 0 %}`.replace('0', materia.id);
                                li.innerHTML = `<a href="${detalle_url}" class="materia">${materia.nombre}</a>`;
                                lista.appendChild(li);
                            });
                        } else {
                            lista.innerHTML = '<p>No hay materias que coincidan</p>';
                        }

                            document.getElementById('submit').addEventListener('click', function (e) {
                                if (encuentra) {

                                    Swal.fire({
                                        title: "Genial",
                                        text: "Se encontró una materia",
                                        imageUrl: 'https://www.lacomuderacing.com/wp-content/uploads/2019/09/El-Cilindro-de-Avellaneda.jpg',
                                        imageWidth: 400,
                                        imageHeight: 200,
                                        imageAlt: "Custom image"
                                    });
                                } else {
                                    Swal.fire({
                                        icon: "error",
                                        title: "Oops...",
                                        text: "No se encontró ninguna materia",
                                    });
                                }

                            })
                        });


                    })


        })


    </script>
{% endblock %}

avance_academico/templates/avance_academico/navbar.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <style>
        nav {
            background-color: #222;
        }
    </style>
    <style>
        /* Ajusta el estilo según tus necesidades */
        .navbar-toggler {
            display: none;
        }
    </style>
</head>
<body>
{% if request.user.is_authenticated %}

    <nav class="navbar navbar-expand-lg navbar-light btn-group-xs custom-navbar">
        <a class="navbar-brand" href="{% url 'avance_academico:index' %} " style="color: rgb(128,128,128)">Avance
            Academico</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'avance_academico:muestra_materias' %}" style="color: azure">
                        Materias <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'avance_academico:lista-profesores' %}" style="color: azure">Profesores
                        <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'avance_academico:anota-materias' %}" style="color: azure">Anotarse<span
                            class="sr-only">(current)</span></a>
                </li>

            </ul>

            <div class="media"
                 style="color: antiquewhite; display: flex; justify-content: flex-end; align-items: center; width: 100%; margin-right: 10px;">
                <div class="media-body" style="text-align: right;">
                    <div class="dropdown">
                        <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton"
                                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            {{ request.user.estudiante.nombre }} {{ request.user.estudiante.apellido }}
                        </button>

                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton">
                            <!-- Aquí puedes agregar más opciones de menú -->
                            <form method="post" action="{% url 'avance_academico:logout' %}" class="navbar-form">
                                {% csrf_token %}
                                <button type="submit" class="dropdown-item"
                                        style="background: none; border: none; padding: 0; font: inherit; cursor: pointer; color: #007bff; text-decoration: none; display: block; width: 100%; text-align: left;">
                                    Cerrar sesión
                                </button>
                            </form>

                            <a class="dropdown-item" href="#"
                               style="color: #007bff; text-decoration: none; display: block; width: 100%; text-align: left; padding-left: 0.5rem;">
                                Tus datos personales
                            </a>
                        </div>
                    </div>
                </div>

                <div style="width: 40px; height: 40px; overflow: hidden; border-radius: 50%;">
                    <img src="/static/{{ request.user.estudiante.apellido }}.jpg" alt="Foto usuario"
                         style="width: 100%; height: 100%; cursor: pointer;" data-toggle="dropdown" aria-haspopup="true"
                         aria-expanded="false" id="dropdownMenuButton">
                </div>
            </div>

            <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
            <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js"></script>
            <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
        </div>
    </nav>
{% else %}
{% endif %}
</body>

</html>